package mrix;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACK, RIGHT_BRACK,
    COLON, SEMICOLON, COMMA, TRANSPOSE,

    ASSIGN, ADD, SUB, MUL, DIV, GREATER, LESS, EQ, NOT,
    DOT_ADD, DOT_SUB, DOT_MUL, DOT_DIV, GREATER_EQ, LESS_EQ, NOT_EQ,
    ADD_ASSIGN, SUB_ASSIGN, MUL_ASSIGN, DIV_ASSIGN,

    IF, ELSE, WHILE, FOR, BREAK, CONTINUE, RETURN,
    AND, OR, 
    EYE, ZEROS, ONES,
    PRINT, ID, INT_NUM, FLOAT_NUM, STRING, FUNCTION, TRUE, FALSE,
    EOF
}
